# inital server setup
---
  - hosts: centos:ubuntu:master
    become: true
    vars:
      centospackages:
        - tree
        - git
        - htop
        - net-snmp
        - youtube-dl 
      ubuntupackages:
        - snmpd      
      admins:
        - localadmin
        - rundeckadmin
    gather_facts: true

    tasks: 
      - name: install packages
        package:
          name: "{{ packages }}"
          state: latest
        tags: packages
    tasks:
      - name: install ubuntu specific named packages
        package:
          name: "{{ ubuntupackages }}"
          state: latest
        tags: ubuntupackages
        when : ansible_distribution == "Ubuntu"

      - name: install base users
        user:
          name: "{{ item }}"
          state: present
          #append: yes
          #groups: sudo
          shell: "/bin/bash"
        with_items:
          - localadmin
          - rundeckadmin
        tags: users 
           #- tasks:
           #- name: update MOTD

      - name: clone chuks repo
        git:
          repo: https://github.com/chukkso/Chukky.git
          dest: /home/ansible/Chukky
        tags: getrepo
